{
    parserClass="com.sazanovich.nikita.gplugin.parser.GParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="G"
    psiImplClassSuffix="Impl"
    psiPackage="com.sazanovich.nikita.gplugin.psi"
    psiImplPackage="com.sazanovich.nikita.gplugin.psi.impl"

    elementTypeHolderClass="com.sazanovich.nikita.gplugin.psi.GTypes"
    elementTypeClass="com.sazanovich.nikita.gplugin.psi.GElementType"
    tokenTypeClass="com.sazanovich.nikita.gplugin.psi.GTokenType"

    tokens=[
    ]
}

GSearch ::= item_*

private item_ ::= (term | COMMENT)

term ::= TILDE_OP term | MINUS_OP term | quote_phrase | query

quote_phrase ::= QUOTE term QUOTE
