{
    parserClass="com.sazanovich.nikita.gplugin.parser.GParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="G"
    psiImplClassSuffix="Impl"
    psiPackage="com.sazanovich.nikita.gplugin.psi"
    psiImplPackage="com.sazanovich.nikita.gplugin.psi.impl"

    elementTypeHolderClass="com.sazanovich.nikita.gplugin.psi.GTypes"
    elementTypeClass="com.sazanovich.nikita.gplugin.psi.GElementType"
    tokenTypeClass="com.sazanovich.nikita.gplugin.psi.GTokenType"
}

GSearch ::= item *

private item ::= (COMMENT | GTerm)

private GTerm ::= term SEMICOLON

term ::= primary_query *

private primary_query ::= quote_query | sign_op primary_query | QUERY

private sign_op ::= TILDE_OP | MINUS_OP

private quote_query ::= QUOTE QUERY QUOTE {pin=1}
